### ISSUE TITLE
上游Git仓库交接

### ISSUE THREAD

**Issue by AndrewLawrence80** [misaka18931/JLU-drcom-auth-nix#1]
Hi，我明年要跑路了，@misaka18931 能接手上游仓库吗

**Comment by misaka18931** [comment]
Hi，我用您的代码用了一年了，谢谢您的仓库Orz。
我对drcom协议不甚理解，这个仓库只是为NixOS打了个包，虽然说因为在日用的关系，以后如果真的遇到问题肯定会尝试自己修就是了。
如果这样可以的话，我很乐意接手。

**Comment by misaka18931** [comment]
另外欢迎加入吉林大学Linux用户协会 1026894631 喵

**Comment by AndrewLawrence80** [comment]
OK未来一年有时间我会写一份DRCOM协议的文档把仓库导向你的fork，另外我在协会的群里潜水(观察)，用NixOS的佬我大概知道是谁😁
